packages:
  - docs
  - packages/*

catalogs:
  2026-08-27-stable:
    "@base-ui/react": 1.7.0
    "@phosphor-icons/react": 2.1.10
    "@storybook/react-vite": 10.5.10
    "@stylexjs/stylex": 0.19.0
    "@stylexjs/unplugin": 0.19.0
    "@types/react": 19.2.18
    "@types/react-dom": 19.2.5
    react: 19.2.8
    react-dom: 19.2.8
    shiki: 3.23.0
    storybook: 10.5.10
    typescript: 7.0.2
    vite: 8.2.2

allowBuilds:
  esbuild: true
  lefthook: true
