import * as stylex from "@stylexjs/stylex";

import { colorPalette } from "./color-palette.stylex";
import { colorVars, shadowVars } from "./semantic.stylex";

export const lightColorTheme = stylex.createTheme(colorVars, {
  bgCanvas: colorPalette.neutral100,
  bgSurface: colorPalette.neutral0,
  bgSurfacePressed: "oklch(97% 0 0)",
  bgInverse: colorPalette.neutral950,
  bgSubtle: colorPalette.neutral50,
  bgRaised: colorPalette.neutral0,
  bgRaisedPressed: "oklch(97% 0 0)",
  bgCurrent: colorPalette.alphaBlack6,
  bgOverlay: colorPalette.alphaBlack40,
  bgSkeleton: colorPalette.neutral200,
  bgActionPrimary: colorPalette.primarySolid,
  bgActionDestructive: colorPalette.redFeedback,
  bgMessageOutgoing: colorPalette.primarySolid,
  bgFeedbackInfo: colorPalette.blueWeak,
  bgFeedbackSuccess: colorPalette.greenWeak,
  bgFeedbackWarning: colorPalette.yellowWeak,
  bgFeedbackError: colorPalette.redWeak,
  fgPrimary: colorPalette.neutral950,
  fgSecondary: colorPalette.neutral600,
  fgTertiary: colorPalette.neutral500,
  fgDisabled: colorPalette.neutral500,
  fgInverse: colorPalette.neutral0,
  fgOnActionPrimary: colorPalette.neutral0,
  fgOnActionDestructive: colorPalette.neutral0,
  fgOnMessageOutgoing: colorPalette.neutral0,
  fgAction: colorPalette.primarySolid,
  fgFeedbackInfo: colorPalette.blueSolid,
  fgFeedbackSuccess: colorPalette.greenFeedback,
  fgFeedbackWarning: colorPalette.yellowFeedback,
  fgFeedbackError: colorPalette.redFeedback,
  strokeDefault: colorPalette.neutral200,
  strokeStrong: colorPalette.neutral300,
  strokeFocus: colorPalette.blueBadge,
  strokeAction: colorPalette.primarySolid,
  strokeFeedbackInfo: colorPalette.blueMuted,
  strokeFeedbackSuccess: colorPalette.greenMuted,
  strokeFeedbackWarning: colorPalette.yellowMuted,
  strokeFeedbackError: colorPalette.redMuted,
  interactionDefault: "transparent",
  interactionHover: colorPalette.alphaBlack6,
  interactionPressed: colorPalette.alphaBlack10,
  interactionSolidHover: colorPalette.alphaWhite10,
  interactionSolidPressed: colorPalette.alphaWhite20,
  interactionSelected: colorPalette.neutral0,
  interactionDisabled: colorPalette.alphaBlack8,
  interactionFocus: colorPalette.blueBadge,
});

export const darkColorTheme = stylex.createTheme(colorVars, {
  bgCanvas: colorPalette.neutral950,
  bgSurface: colorPalette.neutral900,
  bgSurfacePressed: colorPalette.neutral800,
  bgInverse: colorPalette.neutral800,
  bgSubtle: colorPalette.neutral850,
  bgRaised: colorPalette.neutral800,
  bgRaisedPressed: colorPalette.neutral700,
  bgCurrent: colorPalette.alphaWhite8,
  bgOverlay: colorPalette.alphaBlack40,
  bgSkeleton: colorPalette.neutral700,
  bgActionPrimary: colorPalette.neutral100,
  bgActionDestructive: colorPalette.redFeedback,
  bgMessageOutgoing: colorPalette.neutral100,
  bgFeedbackInfo: colorPalette.blueWeakDark,
  bgFeedbackSuccess: colorPalette.greenWeakDark,
  bgFeedbackWarning: colorPalette.yellowWeakDark,
  bgFeedbackError: colorPalette.redWeakDark,
  fgPrimary: colorPalette.neutral100,
  fgSecondary: colorPalette.neutral400,
  fgTertiary: colorPalette.neutral500,
  fgDisabled: colorPalette.neutral500,
  fgInverse: colorPalette.neutral200,
  fgOnActionPrimary: colorPalette.neutral950,
  fgOnActionDestructive: colorPalette.neutral200,
  fgOnMessageOutgoing: colorPalette.neutral950,
  fgAction: colorPalette.primarySolidDark,
  fgFeedbackInfo: colorPalette.blueContrastDark,
  fgFeedbackSuccess: colorPalette.greenContrastDark,
  fgFeedbackWarning: colorPalette.yellowContrastDark,
  fgFeedbackError: colorPalette.redContrastDark,
  strokeDefault: colorPalette.neutral800,
  strokeStrong: colorPalette.neutral700,
  strokeFocus: colorPalette.blueBadge,
  strokeAction: colorPalette.neutral100,
  strokeFeedbackInfo: colorPalette.blueMutedDark,
  strokeFeedbackSuccess: colorPalette.greenMutedDark,
  strokeFeedbackWarning: colorPalette.yellowMutedDark,
  strokeFeedbackError: colorPalette.redMutedDark,
  interactionDefault: "transparent",
  interactionHover: colorPalette.alphaWhite5,
  interactionPressed: colorPalette.alphaWhite10,
  interactionSolidHover: colorPalette.alphaBlack10,
  interactionSolidPressed: colorPalette.alphaBlack20,
  interactionSelected: colorPalette.neutral800,
  interactionDisabled: colorPalette.neutral700,
  interactionFocus: colorPalette.blueBadge,
});

export const lightShadowTheme = stylex.createTheme(shadowVars, {
  subtle: "0 1px 4px oklch(0% 0 0 / 8%)",
  floating: "0 2px 10px oklch(0% 0 0 / 10%)",
  overlay: "0 4px 16px oklch(0% 0 0 / 12%)",
});

export const darkShadowTheme = stylex.createTheme(shadowVars, {
  subtle: "0 0 0 1px oklch(100% 0 0 / 6%), 0 1px 4px oklch(0% 0 0 / 36%)",
  floating: "0 0 0 1px oklch(100% 0 0 / 8%), 0 8px 24px oklch(0% 0 0 / 52%)",
  overlay: "0 0 0 1px oklch(100% 0 0 / 10%), 0 16px 40px oklch(0% 0 0 / 64%)",
});
