import * as stylex from "@stylexjs/stylex";

import { colorPalette } from "./color-palette.stylex";
import { colorVars, shadowVars } from "./tokens.stylex";

export const lightColorTheme = stylex.createTheme(colorVars, {
  bgCanvas: colorPalette.neutral100,
  bgSurface: colorPalette.neutral0,
  bgSurfacePressed: colorPalette.neutral100,
  bgSubtle: colorPalette.neutral50,
  bgRaised: colorPalette.neutral0,
  bgRaisedPressed: colorPalette.neutral100,
  bgActionPrimary: colorPalette.primarySolid,
  bgActionDestructive: colorPalette.redFeedback,
  bgFeedbackInfo: colorPalette.blueWeak,
  bgFeedbackSuccess: colorPalette.greenWeak,
  bgFeedbackWarning: colorPalette.yellowWeak,
  bgFeedbackError: colorPalette.redWeak,
  fgPrimary: colorPalette.neutral950,
  fgSecondary: colorPalette.neutral600,
  fgTertiary: colorPalette.neutral500,
  fgDisabled: colorPalette.alphaBlack50,
  fgInverse: colorPalette.neutral0,
  fgOnActionDestructive: colorPalette.neutral0,
  fgAction: colorPalette.primarySolid,
  fgFeedbackInfo: colorPalette.blueSolid,
  fgFeedbackSuccess: colorPalette.greenFeedback,
  fgFeedbackWarning: colorPalette.yellowFeedback,
  fgFeedbackError: colorPalette.redFeedback,
  strokeDefault: colorPalette.neutral200,
  strokeStrong: colorPalette.neutral300,
  strokeFocus: colorPalette.blueBadge,
  strokeAction: colorPalette.primarySolid,
  strokeFeedbackInfo: colorPalette.blueMuted,
  strokeFeedbackSuccess: colorPalette.greenMuted,
  strokeFeedbackWarning: colorPalette.yellowMuted,
  strokeFeedbackError: colorPalette.redMuted,
  interactionDefault: "transparent",
  interactionHover: colorPalette.alphaBlack6,
  interactionPressed: colorPalette.alphaBlack10,
  interactionSelected: colorPalette.primaryWeak,
  interactionDisabled: colorPalette.alphaBlack8,
  interactionFocus: colorPalette.blueBadge,
});

export const darkColorTheme = stylex.createTheme(colorVars, {
  bgCanvas: colorPalette.neutral950,
  bgSurface: colorPalette.alphaWhite5,
  bgSurfacePressed: colorPalette.alphaWhite10,
  bgSubtle: colorPalette.alphaWhite8,
  bgRaised: colorPalette.neutral850,
  bgRaisedPressed: colorPalette.neutral800,
  bgActionPrimary: colorPalette.primarySolidDark,
  bgActionDestructive: colorPalette.redFeedback,
  bgFeedbackInfo: colorPalette.blueWeakDark,
  bgFeedbackSuccess: colorPalette.greenWeakDark,
  bgFeedbackWarning: colorPalette.yellowWeakDark,
  bgFeedbackError: colorPalette.redWeakDark,
  fgPrimary: colorPalette.neutral50,
  fgSecondary: colorPalette.neutral300,
  fgTertiary: colorPalette.neutral400,
  fgDisabled: colorPalette.alphaWhite50,
  fgInverse: colorPalette.neutral950,
  fgOnActionDestructive: colorPalette.neutral0,
  fgAction: colorPalette.primaryContrastDark,
  fgFeedbackInfo: colorPalette.blueContrastDark,
  fgFeedbackSuccess: colorPalette.greenContrastDark,
  fgFeedbackWarning: colorPalette.yellowContrastDark,
  fgFeedbackError: colorPalette.redContrastDark,
  strokeDefault: colorPalette.neutral700,
  strokeStrong: colorPalette.neutral600,
  strokeFocus: colorPalette.blueSolidDark,
  strokeAction: colorPalette.primarySolidDark,
  strokeFeedbackInfo: colorPalette.blueMutedDark,
  strokeFeedbackSuccess: colorPalette.greenMutedDark,
  strokeFeedbackWarning: colorPalette.yellowMutedDark,
  strokeFeedbackError: colorPalette.redMutedDark,
  interactionDefault: "transparent",
  interactionHover: colorPalette.alphaWhite5,
  interactionPressed: colorPalette.alphaWhite10,
  interactionSelected: colorPalette.primaryWeakDark,
  interactionDisabled: colorPalette.alphaWhite10,
  interactionFocus: colorPalette.blueSolidDark,
});

export const lightShadowTheme = stylex.createTheme(shadowVars, {
  subtle: "0 1px 4px #00000014",
  floating: "0 2px 10px #0000001a",
  overlay: "0 4px 16px #0000001f",
});

export const darkShadowTheme = stylex.createTheme(shadowVars, {
  subtle: "0 1px 4px #00000080",
  floating: "0 2px 10px #000000ad",
  overlay: "0 4px 16px #000000cc",
});
