import * as stylex from "@stylexjs/stylex";

import { colorPalette } from "./color-palette.stylex";
import { colorVars, shadowVars } from "./semantic.stylex";

export const lightColorTheme = stylex.createTheme(colorVars, {
  bgCanvas: colorPalette.neutral100,
  bgSurface: colorPalette.neutral0,
  bgSurfacePressed: "oklch(97% 0 0)",
  bgSubtle: colorPalette.neutral50,
  bgRaised: colorPalette.neutral0,
  bgRaisedPressed: "oklch(97% 0 0)",
  bgActionPrimary: colorPalette.primarySolid,
  bgActionDestructive: colorPalette.redFeedback,
  bgFeedbackInfo: colorPalette.blueWeak,
  bgFeedbackSuccess: colorPalette.greenWeak,
  bgFeedbackWarning: colorPalette.yellowWeak,
  bgFeedbackError: colorPalette.redWeak,
  fgPrimary: colorPalette.neutral950,
  fgSecondary: colorPalette.neutral600,
  fgTertiary: colorPalette.neutral500,
  fgDisabled: colorPalette.alphaBlack50,
  fgInverse: colorPalette.neutral0,
  fgOnActionDestructive: colorPalette.neutral0,
  fgAction: colorPalette.primarySolid,
  fgFeedbackInfo: colorPalette.blueSolid,
  fgFeedbackSuccess: colorPalette.greenFeedback,
  fgFeedbackWarning: colorPalette.yellowFeedback,
  fgFeedbackError: colorPalette.redFeedback,
  strokeDefault: colorPalette.neutral200,
  strokeStrong: colorPalette.neutral300,
  strokeFocus: colorPalette.blueBadge,
  strokeAction: colorPalette.primarySolid,
  strokeFeedbackInfo: colorPalette.blueMuted,
  strokeFeedbackSuccess: colorPalette.greenMuted,
  strokeFeedbackWarning: colorPalette.yellowMuted,
  strokeFeedbackError: colorPalette.redMuted,
  interactionDefault: "transparent",
  interactionHover: colorPalette.alphaBlack6,
  interactionPressed: "oklch(97% 0 0)",
  interactionSolidHover: colorPalette.alphaWhite10,
  interactionSolidPressed: "oklch(97% 0 0)",
  interactionSelected: "oklch(97% 0 0)",
  interactionDisabled: colorPalette.alphaBlack8,
  interactionFocus: colorPalette.blueBadge,
});

export const darkColorTheme = stylex.createTheme(colorVars, {
  bgCanvas: colorPalette.neutral950,
  bgSurface: colorPalette.alphaWhite5,
  bgSurfacePressed: colorPalette.alphaWhite10,
  bgSubtle: colorPalette.alphaWhite8,
  bgRaised: colorPalette.neutral850,
  bgRaisedPressed: colorPalette.neutral800,
  bgActionPrimary: colorPalette.primarySolidDark,
  bgActionDestructive: colorPalette.redFeedback,
  bgFeedbackInfo: colorPalette.blueWeakDark,
  bgFeedbackSuccess: colorPalette.greenWeakDark,
  bgFeedbackWarning: colorPalette.yellowWeakDark,
  bgFeedbackError: colorPalette.redWeakDark,
  fgPrimary: colorPalette.neutral50,
  fgSecondary: colorPalette.neutral300,
  fgTertiary: colorPalette.neutral400,
  fgDisabled: colorPalette.alphaWhite50,
  fgInverse: colorPalette.neutral950,
  fgOnActionDestructive: colorPalette.neutral0,
  fgAction: colorPalette.primaryContrastDark,
  fgFeedbackInfo: colorPalette.blueContrastDark,
  fgFeedbackSuccess: colorPalette.greenContrastDark,
  fgFeedbackWarning: colorPalette.yellowContrastDark,
  fgFeedbackError: colorPalette.redContrastDark,
  strokeDefault: colorPalette.neutral700,
  strokeStrong: colorPalette.neutral600,
  strokeFocus: colorPalette.blueSolidDark,
  strokeAction: colorPalette.primarySolidDark,
  strokeFeedbackInfo: colorPalette.blueMutedDark,
  strokeFeedbackSuccess: colorPalette.greenMutedDark,
  strokeFeedbackWarning: colorPalette.yellowMutedDark,
  strokeFeedbackError: colorPalette.redMutedDark,
  interactionDefault: "transparent",
  interactionHover: colorPalette.alphaWhite5,
  interactionPressed: colorPalette.alphaWhite10,
  interactionSolidHover: colorPalette.alphaBlack10,
  interactionSolidPressed: colorPalette.alphaBlack20,
  interactionSelected: colorPalette.primaryWeakDark,
  interactionDisabled: colorPalette.alphaWhite10,
  interactionFocus: colorPalette.blueSolidDark,
});

export const lightShadowTheme = stylex.createTheme(shadowVars, {
  subtle: "0 1px 4px oklch(0% 0 0 / 8%)",
  floating: "0 2px 10px oklch(0% 0 0 / 10%)",
  overlay: "0 4px 16px oklch(0% 0 0 / 12%)",
});

export const darkShadowTheme = stylex.createTheme(shadowVars, {
  subtle: "0 1px 4px oklch(0% 0 0 / 50%)",
  floating: "0 2px 10px oklch(0% 0 0 / 68%)",
  overlay: "0 4px 16px oklch(0% 0 0 / 80%)",
});
