import {
  colorVars,
  motionVars,
  opacityVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@cachette/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: { minWidth: 0, width: "100%" },
  item: {
    borderBottomColor: colorVars.strokeDefault,
    borderBottomStyle: "solid",
    borderBottomWidth: sizeVars.stroke,
  },
  header: { display: "flex", margin: 0 },
  trigger: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: colorVars.fgPrimary,
    cursor: "pointer",
    display: "flex",
    flex: 1,
    fontFamily: typographyVars.fontFamily,
    fontSize: typographyVars.fontSizeSm,
    fontWeight: typographyVars.fontWeightMedium,
    justifyContent: "space-between",
    lineHeight: typographyVars.lineHeightNormal,
    outline: "none",
    paddingBlock: spacingVars.space4,
    paddingInline: 0,
    textAlign: "start",
    transitionDuration: motionVars.durationFast,
    transitionProperty: "color",
    ":hover": { textDecoration: "underline", textUnderlineOffset: spacingVars.space1 },
    ":focus-visible": {
      outlineColor: colorVars.strokeFocus,
      outlineOffset: sizeVars.focusRing,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
    ":disabled": { cursor: "not-allowed", opacity: opacityVars.disabled },
  },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "1rem",
    justifyContent: "center",
    transitionDuration: motionVars.durationNormal,
    transitionProperty: "transform",
    width: "1rem",
  },
  iconDisabled: { opacity: opacityVars.disabled },
  panel: {
    color: colorVars.fgSecondary,
    fontSize: typographyVars.fontSizeSm,
    lineHeight: typographyVars.lineHeightNormal,
    minWidth: 0,
    paddingBottom: spacingVars.space4,
    paddingInlineEnd: spacingVars.space6,
    width: "100%",
  },
});
