import {
  colorVars,
  radiusVars,
  shadowVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@cachette/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: { position: "relative" },
  list: {
    alignItems: "center",
    display: "flex",
    gap: spacingVars.space1,
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  trigger: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: radiusVars.md,
    color: colorVars.fgPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: typographyVars.fontFamily,
    fontSize: typographyVars.fontSizeSm,
    fontWeight: typographyVars.fontWeightMedium,
    gap: spacingVars.space1,
    height: sizeVars.controlMd,
    outline: "none",
    paddingInline: spacingVars.space4,
    ":hover": { backgroundColor: colorVars.bgSubtle },
    ":focus-visible": {
      outlineColor: colorVars.strokeFocus,
      outlineOffset: sizeVars.stroke,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
  },
  triggerOpen: { backgroundColor: colorVars.bgSubtle },
  icon: { alignItems: "center", display: "inline-flex" },
  link: {
    borderRadius: radiusVars.md,
    color: colorVars.fgPrimary,
    display: "block",
    outline: "none",
    padding: spacingVars.space3,
    textDecoration: "none",
    ":hover": { backgroundColor: colorVars.bgSubtle },
    ":focus-visible": {
      backgroundColor: colorVars.bgSubtle,
      outlineColor: colorVars.strokeFocus,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
  },
  positioner: { zIndex: 60 },
  popup: {
    backgroundColor: colorVars.bgRaised,
    borderColor: colorVars.strokeDefault,
    borderRadius: radiusVars.md,
    borderStyle: "solid",
    borderWidth: sizeVars.stroke,
    boxShadow: shadowVars.floating,
    color: colorVars.fgPrimary,
    minWidth: "20rem",
    outline: "none",
    overflow: "hidden",
  },
  viewport: { fontFamily: typographyVars.fontFamily, padding: spacingVars.space2 },
});
