import {
  colorVars,
  motionVars,
  radiusVars,
  shadowVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@cachette/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    justifyContent: "center",
    maxWidth: "max-content",
    position: "relative",
    zIndex: 10,
  },
  list: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    gap: 0,
    justifyContent: "center",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  item: { position: "relative" },
  trigger: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: radiusVars.md,
    color: colorVars.fgPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: typographyVars.fontFamily,
    fontSize: typographyVars.fontSizeSm,
    fontWeight: typographyVars.fontWeightMedium,
    gap: spacingVars.space1,
    height: sizeVars.controlMd,
    outline: "none",
    paddingInline: spacingVars.space3,
    transitionDuration: motionVars.durationFast,
    transitionProperty: "background-color, color",
    ":hover": { backgroundColor: colorVars.bgSubtle },
    ":focus-visible": {
      outlineColor: colorVars.strokeFocus,
      outlineOffset: sizeVars.stroke,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
  },
  triggerOpen: { backgroundColor: colorVars.interactionHover },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    position: "relative",
    top: sizeVars.stroke,
  },
  iconClosed: {
    alignItems: "center",
    display: "inline-flex",
    ":is([data-popup-open] *)": { display: "none" },
  },
  iconOpen: {
    alignItems: "center",
    display: "none",
    ":is([data-popup-open] *)": { display: "inline-flex" },
  },
  content: {
    height: "100%",
    padding: spacingVars.space1,
    transitionDuration: motionVars.durationNormal,
    transitionProperty: "opacity, transform",
    width: "auto",
  },
  contentStartingFromLeft: { opacity: 0, transform: "translateX(-50%)" },
  contentStartingFromRight: { opacity: 0, transform: "translateX(50%)" },
  contentEndingToLeft: { opacity: 0, transform: "translateX(-50%)" },
  contentEndingToRight: { opacity: 0, transform: "translateX(50%)" },
  link: {
    alignItems: "center",
    borderRadius: radiusVars.md,
    color: colorVars.fgPrimary,
    display: "flex",
    gap: spacingVars.space2,
    outline: "none",
    padding: spacingVars.space2,
    textDecoration: "none",
    transitionDuration: motionVars.durationFast,
    transitionProperty: "background-color, color",
    ":hover": { backgroundColor: colorVars.bgSubtle },
    ":focus-visible": {
      backgroundColor: colorVars.bgSubtle,
      outlineColor: colorVars.strokeFocus,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
  },
  positioner: {
    height: "var(--positioner-height)",
    maxWidth: "var(--available-width)",
    transitionDuration: motionVars.durationNormal,
    transitionProperty: "inset, width, height",
    width: "var(--positioner-width)",
    zIndex: 60,
  },
  popup: {
    backgroundColor: colorVars.bgRaised,
    borderColor: colorVars.strokeDefault,
    borderRadius: radiusVars.md,
    borderStyle: "solid",
    borderWidth: sizeVars.stroke,
    boxShadow: shadowVars.floating,
    color: colorVars.fgPrimary,
    height: "var(--popup-height)",
    outline: "none",
    overflow: "hidden",
    position: "relative",
    transformOrigin: "var(--transform-origin)",
    transitionDuration: motionVars.durationNormal,
    transitionProperty: "opacity, transform, width, height",
    width: "var(--popup-width)",
  },
  popupTransitioning: { opacity: 0, transform: "scale(0.9)" },
  viewport: {
    fontFamily: typographyVars.fontFamily,
    height: "100%",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
});
