import {
  colorVars,
  motionVars,
  radiusVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@dumo/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: colorVars.bgSurface,
    borderColor: colorVars.strokeDefault,
    borderRadius: radiusVars.sm,
    borderStyle: "solid",
    borderWidth: sizeVars.stroke,
    color: colorVars.fgPrimary,
    display: "flex",
    minWidth: 0,
    position: "relative",
    transitionDuration: motionVars.durationFast,
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: motionVars.easingStandard,
  },
  horizontal: { flexDirection: "row" },
  vertical: { alignItems: "stretch", flexDirection: "column" },
  sizeDefault: { gap: spacingVars.space3, minHeight: "4.5rem", padding: spacingVars.space3 },
  sm: { gap: spacingVars.space2, minHeight: sizeVars.touchTarget, padding: spacingVars.space2 },
  xs: { gap: spacingVars.space2, minHeight: sizeVars.controlMd, padding: spacingVars.space1 },
  error: {
    backgroundColor: colorVars.bgFeedbackError,
    borderColor: colorVars.strokeFeedbackError,
  },
  media: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    overflow: "hidden",
  },
  mediaicon: {
    backgroundColor: colorVars.bgSubtle,
    borderRadius: radiusVars.sm,
    color: colorVars.fgSecondary,
    height: sizeVars.controlLg,
    width: sizeVars.controlLg,
  },
  mediaimage: {
    borderRadius: radiusVars.sm,
    height: "3rem",
    objectFit: "cover",
    width: "3rem",
  },
  content: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: spacingVars.space1,
    minWidth: 0,
  },
  title: {
    fontSize: typographyVars.fontSizeSm,
    fontWeight: typographyVars.fontWeightMedium,
    lineHeight: typographyVars.lineHeightTight,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  description: {
    color: colorVars.fgSecondary,
    fontSize: typographyVars.fontSizeXs,
    lineHeight: typographyVars.lineHeightNormal,
    margin: 0,
  },
  actions: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: spacingVars.space1,
    position: "relative",
    zIndex: 2,
  },
  action: { minWidth: sizeVars.controlSm, paddingInline: spacingVars.space2 },
  trigger: {
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "inherit",
    cursor: "pointer",
    inset: 0,
    outline: {
      default: "none",
      ":focus-visible": `${sizeVars.focusRing} solid ${colorVars.strokeFocus}`,
    },
    outlineOffset: { default: 0, ":focus-visible": 2 },
    position: "absolute",
    zIndex: 1,
  },
  group: {
    display: "flex",
    gap: spacingVars.space3,
    overflowX: "auto",
    paddingBlock: spacingVars.space1,
    scrollSnapType: "x proximity",
    width: "100%",
  },
});
