import {
  colorVars,
  opacityVars,
  radiusVars,
  shadowVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@cachette/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  positioner: { zIndex: 60 },
  popup: {
    backgroundColor: colorVars.bgRaised,
    borderColor: colorVars.strokeDefault,
    borderRadius: radiusVars.md,
    borderStyle: "solid",
    borderWidth: sizeVars.stroke,
    boxShadow: shadowVars.floating,
    color: colorVars.fgPrimary,
    minWidth: "12rem",
    outline: "none",
    padding: spacingVars.space1,
  },
  item: {
    alignItems: "center",
    borderRadius: radiusVars.sm,
    color: colorVars.fgPrimary,
    cursor: "default",
    display: "flex",
    fontFamily: typographyVars.fontFamily,
    fontSize: typographyVars.fontSizeSm,
    gap: spacingVars.space2,
    minHeight: sizeVars.controlSm,
    outline: "none",
    paddingInline: spacingVars.space2,
    position: "relative",
    userSelect: "none",
    ":disabled": { opacity: opacityVars.disabled },
  },
  itemHighlighted: { backgroundColor: colorVars.interactionHover },
  inset: { paddingInlineStart: spacingVars.space8 },
  destructive: { color: colorVars.fgFeedbackError },
  choiceItem: { paddingInlineStart: spacingVars.space8 },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    insetInlineStart: spacingVars.space2,
    justifyContent: "center",
    position: "absolute",
  },
  radioDot: {
    backgroundColor: "currentColor",
    borderRadius: radiusVars.full,
    height: spacingVars.space2,
    width: spacingVars.space2,
  },
  label: {
    color: colorVars.fgSecondary,
    fontSize: typographyVars.fontSizeXs,
    fontWeight: typographyVars.fontWeightMedium,
    paddingBlock: spacingVars.space2,
    paddingInline: spacingVars.space2,
  },
  separator: {
    backgroundColor: colorVars.strokeDefault,
    height: sizeVars.stroke,
    marginBlock: spacingVars.space1,
  },
  shortcut: {
    color: colorVars.fgTertiary,
    fontSize: typographyVars.fontSizeXs,
    marginInlineStart: "auto",
  },
  subIcon: { marginInlineStart: "auto" },
});
