import {
  colorVars,
  radiusVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@dumo/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: colorVars.bgSurface,
    borderColor: colorVars.strokeDefault,
    borderRadius: radiusVars.sm,
    borderStyle: "solid",
    borderWidth: sizeVars.stroke,
    display: "flex",
    flexWrap: "wrap",
    minHeight: sizeVars.controlMd,
    minWidth: 0,
    width: "100%",
    ":focus-within": {
      borderColor: colorVars.strokeFocus,
      outlineColor: colorVars.strokeFocus,
      outlineOffset: sizeVars.stroke,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
  },
  invalid: { borderColor: colorVars.strokeFeedbackError },
  addon: {
    alignItems: "center",
    color: colorVars.fgSecondary,
    cursor: "text",
    display: "flex",
    flexShrink: 0,
    fontSize: typographyVars.fontSizeSm,
    gap: spacingVars.space2,
    minHeight: sizeVars.controlMd,
  },
  "inline-start": { order: -1, paddingInlineStart: spacingVars.space3 },
  "inline-end": { order: 1, paddingInlineEnd: spacingVars.space3 },
  "block-start": {
    alignSelf: "stretch",
    justifyContent: "flex-start",
    order: -1,
    paddingInline: spacingVars.space3,
    width: "100%",
  },
  "block-end": {
    alignSelf: "stretch",
    justifyContent: "flex-start",
    order: 1,
    paddingInline: spacingVars.space3,
    width: "100%",
  },
  control: {
    appearance: "none",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: radiusVars.sm,
    boxShadow: "none",
    flex: 1,
    minWidth: 0,
    outline: "none",
    ":hover": { borderColor: "transparent" },
    ":focus-visible": {
      borderColor: "transparent",
      outlineColor: "transparent",
      outlineOffset: 0,
      outlineStyle: "none",
      outlineWidth: 0,
    },
  },
  textarea: { minHeight: "5rem" },
  button: { flexShrink: 0, margin: spacingVars.space1 },
  text: {
    alignItems: "center",
    color: colorVars.fgSecondary,
    display: "inline-flex",
    fontSize: typographyVars.fontSizeSm,
    gap: spacingVars.space2,
  },
});
