import {
  colorVars,
  motionVars,
  radiusVars,
  sizeVars,
  spacingVars,
  typographyVars,
} from "@cachette/tokens/tokens.stylex";
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: { minWidth: 0, width: "100%" },
  trigger: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: colorVars.bgSurface,
    borderColor: colorVars.strokeDefault,
    borderRadius: radiusVars.md,
    borderStyle: "solid",
    borderWidth: sizeVars.stroke,
    color: colorVars.fgPrimary,
    cursor: "pointer",
    display: "flex",
    fontFamily: typographyVars.fontFamily,
    fontSize: typographyVars.fontSizeSm,
    fontWeight: typographyVars.fontWeightMedium,
    gap: spacingVars.space2,
    justifyContent: "space-between",
    minHeight: sizeVars.controlMd,
    outline: "none",
    paddingInline: spacingVars.space3,
    width: "100%",
    ":hover": { backgroundColor: colorVars.bgSurfacePressed },
    ":focus-visible": {
      outlineColor: colorVars.strokeFocus,
      outlineOffset: sizeVars.focusRing,
      outlineStyle: "solid",
      outlineWidth: sizeVars.focusRing,
    },
  },
  panel: {
    color: colorVars.fgSecondary,
    fontSize: typographyVars.fontSizeSm,
    lineHeight: typographyVars.lineHeightNormal,
    minWidth: 0,
    paddingBlock: spacingVars.space3,
    paddingInline: spacingVars.space3,
    width: "100%",
  },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    transitionDuration: motionVars.durationNormal,
    transitionProperty: "transform",
  },
});
